const express = require('express')
const app = express()
const dotenv = require('dotenv')
dotenv.config()
const cors = require('cors')
const connectDB = require('./db-configuration/connect.js')
const authRoutes = require('./routes/authRoutes.js')
const jobRoutes = require('./routes/jobRoutes.js')
const applicationRoutes = require('./routes/applicationRoutes.js')
const PORT = process.env.PORT || 8000

app.use(express.json())
app.use(cors())
connectDB()
app.use('/api/auth', authRoutes)
app.use('/api/applications', applicationRoutes)
app.use('/api/jobs', jobRoutes)
app.listen(PORT, ()=>{
    console.log(`Server Connect On This Port ${process.env.PORT}`)
})